export const appHtml = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Feishu Profile Control</title>
  <script src="https://unpkg.com/lucide@latest"></script>
  <style>
    :root { color-scheme: dark; --ink:#e9eeea; --muted:#8d9891; --line:#29312e; --deep:#111514; --panel:#171d1b; --panel2:#1c2421; --green:#6ce2ae; --orange:#ffa95c; --red:#f27878; --blue:#77c9d1; }
    * { box-sizing:border-box; letter-spacing:0; } body { margin:0; min-width:320px; background:var(--deep); color:var(--ink); font:13px/1.45 Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    button, input, select { font:inherit; } button { color:inherit; } .shell { display:grid; grid-template-columns:218px minmax(0,1fr); min-height:100vh; }
    .side { border-right:1px solid var(--line); padding:20px 12px; display:flex; flex-direction:column; gap:18px; background:#131817; } .brand { padding:0 10px; display:flex; align-items:center; gap:9px; font-weight:700; } .brand-mark { width:25px; height:25px; display:grid; place-items:center; border:1px solid var(--green); color:var(--green); } .brand small { display:block; color:var(--muted); font-size:10px; font-weight:500; text-transform:uppercase; }
    .nav { display:grid; gap:3px; } .nav a { color:var(--muted); text-decoration:none; padding:9px 10px; border-left:2px solid transparent; display:flex; justify-content:space-between; align-items:center; } .nav a:first-child { color:var(--ink); background:#1a211e; border-left-color:var(--green); } .nav strong { font-size:11px; font-weight:600; color:var(--green); }
    .side-bottom { margin-top:auto; border-top:1px solid var(--line); padding:13px 10px 0; color:var(--muted); font-size:11px; } .dot { display:inline-block; width:7px; height:7px; margin-right:6px; background:var(--green); box-shadow:0 0 9px rgba(108,226,174,.7); }
    main { min-width:0; } .topbar { height:70px; border-bottom:1px solid var(--line); display:flex; align-items:center; justify-content:space-between; padding:0 28px; } .crumb { color:var(--muted); font-size:12px; } .crumb b { color:var(--ink); font-weight:600; } .actions { display:flex; align-items:center; gap:9px; } .icon-button { display:grid; place-items:center; width:32px; height:32px; border:1px solid var(--line); background:transparent; cursor:pointer; } .icon-button:hover { border-color:var(--blue); color:var(--blue); } .icon-button svg { width:15px; }
    .content { max-width:1500px; margin:0 auto; padding:28px; } .heading { display:flex; justify-content:space-between; align-items:end; gap:18px; margin-bottom:22px; } h1 { font-size:22px; line-height:1.1; margin:0 0 5px; font-weight:650; } .heading p { color:var(--muted); margin:0; } .updated { color:var(--muted); font-variant-numeric:tabular-nums; font-size:11px; }
    .metrics { display:grid; grid-template-columns:repeat(4, minmax(0,1fr)); border:1px solid var(--line); margin-bottom:26px; } .metric { min-height:86px; padding:15px 17px; border-right:1px solid var(--line); } .metric:last-child { border-right:0; } .metric span { display:block; color:var(--muted); font-size:11px; } .metric b { display:block; font-size:24px; line-height:1.1; font-weight:600; margin-top:6px; font-variant-numeric:tabular-nums; } .metric b.ok { color:var(--green); } .metric b.warn { color:var(--orange); }
    section { margin-bottom:28px; } .section-title { display:flex; align-items:center; justify-content:space-between; border-bottom:1px solid var(--line); padding-bottom:10px; margin-bottom:12px; } h2 { margin:0; font-size:12px; text-transform:uppercase; color:#c7d1ca; font-weight:650; } .section-title span { color:var(--muted); font-size:11px; }
    .table-wrap { overflow:auto; border:1px solid var(--line); background:var(--panel); } table { width:100%; border-collapse:collapse; min-width:810px; } #users table { min-width:620px; } th { color:var(--muted); height:38px; padding:0 13px; text-align:left; font-size:10px; font-weight:600; text-transform:uppercase; background:#151a18; border-bottom:1px solid var(--line); } td { height:62px; padding:10px 13px; border-bottom:1px solid var(--line); vertical-align:middle; } tr:last-child td { border-bottom:0; } .name { font-weight:620; } .sub { display:block; margin-top:3px; color:var(--muted); font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; max-width:270px; } .status { display:inline-flex; align-items:center; gap:6px; color:var(--muted); font-size:11px; } .status i { width:7px; height:7px; background:var(--orange); } .status.ok i { background:var(--green); box-shadow:0 0 8px rgba(108,226,174,.48); } .status.off i { background:var(--red); } .pills { display:flex; gap:4px; flex-wrap:wrap; } .pill { border:1px solid var(--line); padding:2px 6px; color:var(--muted); font-size:10px; } .pill.good { color:var(--green); border-color:rgba(108,226,174,.35); } .row-actions { display:flex; justify-content:flex-end; gap:5px; } .compact { height:28px; padding:0 8px; border:1px solid var(--line); background:transparent; font-size:11px; cursor:pointer; white-space:nowrap; } .compact:hover { border-color:var(--blue); color:var(--blue); } .compact.sync { background:#264738; border-color:#326949; color:#e6ffef; } .compact.sync:hover { background:#315e47; color:white; }
    .lower { display:grid; grid-template-columns:minmax(0,1fr) 390px; gap:20px; } .audit { border:1px solid var(--line); background:var(--panel); } .audit-row { display:grid; grid-template-columns:142px 84px 78px minmax(0,1fr); gap:12px; padding:11px 13px; border-bottom:1px solid var(--line); font-size:11px; } .audit-row:last-child { border-bottom:0; } .audit-row time, .audit-row .action { color:var(--muted); } .result { color:var(--green); text-transform:uppercase; } .result.failed { color:var(--red); } .empty { padding:26px 13px; color:var(--muted); font-size:12px; }
    .right-panel { border:1px solid var(--line); background:var(--panel); } .right-panel form { display:grid; gap:11px; padding:14px; } label { display:grid; gap:5px; color:var(--muted); font-size:10px; text-transform:uppercase; } input, select { width:100%; min-width:0; color:var(--ink); background:#111614; border:1px solid var(--line); padding:8px 9px; outline:none; border-radius:0; } input:focus, select:focus { border-color:var(--blue); } .form-grid { display:grid; grid-template-columns:1fr 1fr; gap:10px; } .check { display:flex; align-items:center; gap:8px; text-transform:none; font-size:11px; } .check input { width:14px; height:14px; accent-color:var(--green); } .form-actions { display:flex; justify-content:flex-end; gap:7px; margin-top:4px; } .form-actions button { height:30px; padding:0 10px; border:1px solid var(--line); background:transparent; cursor:pointer; } .form-actions button.primary { background:#264738; border-color:#326949; }
    dialog { width:min(440px, calc(100vw - 28px)); border:1px solid var(--line); padding:0; color:var(--ink); background:#171d1b; } dialog::backdrop { background:rgba(0,0,0,.66); } .modal-head { padding:15px 16px 10px; border-bottom:1px solid var(--line); } .modal-head h3 { margin:0; font-size:14px; } .modal-body { padding:15px 16px; color:var(--muted); } .modal-body code { color:var(--green); background:#111614; padding:2px 4px; } .modal-actions { display:flex; justify-content:flex-end; gap:8px; padding:0 16px 16px; } .modal-actions button { border:1px solid var(--line); background:transparent; min-height:31px; padding:0 10px; color:var(--ink); cursor:pointer; } .modal-actions .danger { background:#5d3030; border-color:#8d4848; }
    #toast { position:fixed; right:20px; bottom:20px; width:min(470px, calc(100vw - 40px)); background:#202925; border:1px solid var(--line); padding:11px 13px; color:var(--ink); font-size:12px; box-shadow:0 12px 32px rgba(0,0,0,.28); white-space:pre-wrap; display:none; } #toast.error { border-color:#8d4848; } 
    @media (max-width:1180px) { .shell { grid-template-columns:1fr; } .side { display:none; } .topbar { padding:0 22px; height:58px; } .content { padding:22px; } .lower { grid-template-columns:1fr; } .right-panel { order:-1; } }
    @media (max-width:760px) { .content { padding:20px 14px; } .metrics { grid-template-columns:1fr 1fr; } .metric:nth-child(2) { border-right:0; } .metric:nth-child(-n+2) { border-bottom:1px solid var(--line); } }
    @media (max-width:520px) { .heading { display:block; } .updated { display:block; margin-top:9px; } .metrics { grid-template-columns:1fr; } .metric { border-right:0; border-bottom:1px solid var(--line); } .metric:last-child { border-bottom:0; } .form-grid { grid-template-columns:1fr; } .audit-row { grid-template-columns:1fr 1fr; gap:5px; } .audit-row .detail { grid-column:1/-1; } }
  </style>
</head>
<body>
  <div class="shell">
    <aside class="side"><div class="brand"><span class="brand-mark"><i data-lucide="orbit"></i></span><span>FEISHU<small>Profile control</small></span></div><nav class="nav"><a href="#agents"><span>Agent Profiles</span><strong id="nav-agents">0</strong></a><a href="#users"><span>User Profiles</span><strong id="nav-users">0</strong></a><a href="#audit"><span>Sync Log</span><strong id="nav-audit">0</strong></a></nav><div class="side-bottom"><span class="dot"></span>LOCAL CONTROL PLANE<br><span id="registry-path">Registry unavailable</span></div></aside>
    <main><header class="topbar"><div class="crumb">Local / <b>Profile Control</b></div><div class="actions"><button class="icon-button" id="refresh" title="刷新本地状态"><i data-lucide="refresh-cw"></i></button></div></header><div class="content">
      <div class="heading"><div><h1>Backend profiles</h1><p>127.0.0.1 · local</p></div><span class="updated" id="updated">Loading local state...</span></div>
      <div class="metrics"><div class="metric"><span>AGENT PROFILES</span><b id="metric-agents">-</b></div><div class="metric"><span>READY TO SYNC</span><b class="ok" id="metric-ready">-</b></div><div class="metric"><span>USER IDENTITIES</span><b id="metric-users">-</b></div><div class="metric"><span>AUTH ATTENTION</span><b class="warn" id="metric-auth">-</b></div></div>
      <section id="agents"><div class="section-title"><h2>Agent Profiles</h2><span>Deployments remain local until an explicit sync</span></div><div class="table-wrap"><table><thead><tr><th>Profile / Runtime</th><th>Feishu Application</th><th>Local Readiness</th><th>Source & Artifacts</th><th></th></tr></thead><tbody id="agents-body"></tbody></table></div></section>
      <section id="users"><div class="section-title"><h2>User Profiles</h2><span>Identity is shown without raw Feishu identifiers</span></div><div class="table-wrap"><table><thead><tr><th>User</th><th>CLI Profile</th><th>Application</th><th>Token Status</th></tr></thead><tbody id="users-body"></tbody></table></div></section>
      <div class="lower"><section id="audit"><div class="section-title"><h2>Sync Audit</h2><span>Latest 100 local records</span></div><div class="audit" id="audit-body"></div></section><section class="right-panel"><div class="section-title" style="padding:12px 14px 10px;margin:0"><h2>Edit Agent Profile</h2><span id="edit-label">Select a profile</span></div><form id="agent-form"><div class="form-grid"><label>Name<input name="name" required disabled></label><label>CLI Profile<input name="cliProfile" required disabled></label></div><div class="form-grid"><label>Runtime<select name="runtime" disabled><option value="langbot">LangBot</option><option value="codex">Codex</option></select></label><label>Enabled<select name="enabled" disabled><option value="true">Enabled</option><option value="false">Paused</option></select></label></div><label>Agent source<input name="sourceDir" required disabled></label><label>Artifact output<input name="artifactDir" required disabled></label><label>Deploy directory<input name="deployDir" disabled></label><div class="form-actions"><button type="button" id="clear-edit">Clear</button><button type="submit" class="primary" id="save-agent" disabled>Save local profile</button></div></form></section></div>
    </div></main>
  </div>
  <dialog id="sync-dialog"><div class="modal-head"><h3>Confirm deployment sync</h3></div><div class="modal-body"><p>This will call the configured local deployment script and may create or update LangBot resources.</p><label>Type <code id="confirm-text"></code><input id="confirmation" autocomplete="off"></label></div><div class="modal-actions"><button id="cancel-sync">Cancel</button><button class="danger" id="confirm-sync">Run sync</button></div></dialog><div id="toast"></div>
  <script>
    const app = { state:null, editing:null, pending:null };
    const API_BASE = window.__FEISHU_API_BASE__ || '';
    const $ = (selector) => document.querySelector(selector);
    const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const fmtTime = value => value ? new Intl.DateTimeFormat('zh-CN', {month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)) : '-';
    async function request(url, options) { const response = await fetch(API_BASE+url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
    async function load() { try { const state = await request('/api/state'); app.state=state; render(); } catch(error) { toast(error.message, true); } }
    function readiness(agent) { const r=agent.readiness; return r.sourceReady && r.artifactsReady && r.deployReady && r.cliProfileReady; }
    function render() { const s=app.state; const ready=s.agents.filter(readiness).length; const auth=s.users.filter(u=>u.tokenStatus !== 'valid').length; $('#metric-agents').textContent=s.agents.length; $('#metric-ready').textContent=ready; $('#metric-users').textContent=s.users.length; $('#metric-auth').textContent=auth; $('#nav-agents').textContent=s.agents.length; $('#nav-users').textContent=s.users.length; $('#nav-audit').textContent=s.audit.length; $('#updated').textContent='LOCAL SNAPSHOT · '+fmtTime(s.generatedAt); $('#registry-path').textContent=s.registryFile.split('/').slice(-2).join('/');
      $('#agents-body').innerHTML=s.agents.length?s.agents.map(agent=>{ const r=agent.readiness, good=readiness(agent); const pills=[['manifest',r.sourceReady],['artifacts',r.artifactsReady],['cli profile',r.cliProfileReady]].map(([t,v])=>'<span class="pill '+(v?'good':'')+'">'+t+'</span>').join(''); return '<tr><td><span class="name">'+esc(agent.name)+'</span><span class="sub">'+esc(agent.runtime)+' · '+(agent.enabled?'enabled':'paused')+'</span></td><td><span class="name">'+esc(agent.cliProfile)+'</span><span class="sub">'+esc(agent.cli?.appIdSuffix || 'not detected')+'</span></td><td><span class="status '+(good?'ok':'off')+'"><i></i>'+ (good?'ready':'attention')+'</span><span class="sub">token: '+esc(agent.cli?.tokenStatus || 'unknown')+'</span></td><td><div class="pills">'+pills+'</div><span class="sub">'+esc(agent.sourceDir)+'</span></td><td><div class="row-actions"><button class="compact" title="Edit profile" onclick="editAgent(\''+esc(agent.id)+'\')"><i data-lucide="settings-2"></i></button><button class="compact" onclick="act(\''+esc(agent.id)+'\',\'preflight\')">Preflight</button><button class="compact" onclick="act(\''+esc(agent.id)+'\',\'generate\')">Generate</button><button class="compact sync" onclick="confirmDeploy(\''+esc(agent.id)+'\')">Sync</button></div></td></tr>'; }).join(''):'<tr><td colspan="5" class="empty">No local agent profiles are registered.</td></tr>';
      $('#users-body').innerHTML=s.users.length?s.users.map(u=>'<tr><td><span class="name">'+esc(u.displayName)+'</span><span class="sub">user identity</span></td><td>'+esc(u.cliProfile)+'</td><td>'+esc(u.application)+'</td><td><span class="status '+(u.tokenStatus==='valid'?'ok':'')+'"><i></i>'+esc(u.tokenStatus)+'</span></td></tr>').join(''):'<tr><td colspan="4" class="empty">No CLI user authorization is stored locally.</td></tr>';
      $('#audit-body').innerHTML=s.audit.length?s.audit.map(a=>'<div class="audit-row"><time>'+fmtTime(a.at)+'</time><span class="action">'+esc(a.agentId)+' / '+esc(a.action)+'</span><span class="result '+(a.status==='failed'?'failed':'')+'">'+esc(a.status)+'</span><span class="detail">'+esc(a.detail.replace(/\n/g,' '))+'</span></div>').join(''):'<div class="empty">No local sync activity yet.</div>';
      lucide.createIcons(); if (app.editing) populateForm(app.editing); }
    window.editAgent = id => { app.editing=app.state.agents.find(a=>a.id===id); populateForm(app.editing); $('#agent-form').scrollIntoView({behavior:'smooth',block:'center'}); };
    function populateForm(agent) { const form=$('#agent-form'); $('#edit-label').textContent=agent.name; for (const el of form.elements) { if (el.name in agent) { el.disabled=false; el.value=String(agent[el.name] ?? ''); } } $('#save-agent').disabled=false; }
    $('#clear-edit').onclick=()=>{ app.editing=null; $('#edit-label').textContent='Select a profile'; $('#agent-form').reset(); [...$('#agent-form').elements].forEach(e=>e.disabled=true); $('#clear-edit').disabled=false; };
    $('#agent-form').onsubmit=async event=>{ event.preventDefault(); if(!app.editing)return; const f=new FormData(event.currentTarget); const payload=Object.fromEntries(f.entries()); payload.enabled=payload.enabled==='true'; try { const state=await request('/api/agents/'+app.editing.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); app.state=state; toast('Local profile saved.'); render(); } catch(error) { toast(error.message,true); } };
    window.act=async (id, action)=>{ try { const data=await request('/api/agents/'+id+'/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})}); app.state=data.state; toast(data.detail); render(); } catch(error) { toast(error.message,true); } };
    window.confirmDeploy=id=>{ app.pending=id; $('#confirm-text').textContent='SYNC '+id; $('#confirmation').value=''; $('#sync-dialog').showModal(); $('#confirmation').focus(); };
    $('#cancel-sync').onclick=()=>$('#sync-dialog').close(); $('#confirm-sync').onclick=async()=>{ const confirmation=$('#confirmation').value; if(confirmation!=='SYNC '+app.pending){ toast('输入 SYNC '+app.pending+' 后才会执行部署同步。',true); return; } try { const data=await request('/api/agents/'+app.pending+'/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'deploy',confirmation})}); $('#sync-dialog').close(); app.state=data.state; toast(data.detail); render(); } catch(error) { toast(error.message,true); } };
    $('#refresh').onclick=load; let toastTimer; function toast(message, error=false) { const target=$('#toast'); target.textContent=message; target.className=error?'error':''; target.style.display='block'; clearTimeout(toastTimer); toastTimer=setTimeout(()=>target.style.display='none',5500); } load();
  </script>
</body>
</html>`;
